-- Script adaptado para Oracle
-- En Oracle/APEX no se usa USE GestionTramite;

CREATE TABLE TipoEstado (
    codTipoEstado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreTipoEstado VARCHAR2(100) NOT NULL
);

CREATE TABLE TipoTramite (
    codTipoTramite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraBajaTT TIMESTAMP,
    nombreTipoTramite VARCHAR2(100) NOT NULL,
    cantidadDiasMaximoDocumentacion NUMBER NOT NULL
);

CREATE TABLE EstadoTramite (
    codEstadoTramite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraBajaEstadoTramite TIMESTAMP,
    nombreEstadoTramite VARCHAR2(100) NOT NULL,
    codTipoEstado NUMBER NOT NULL,

    CONSTRAINT estado_tramite_tipo_estado_fk
        FOREIGN KEY (codTipoEstado)
        REFERENCES TipoEstado(codTipoEstado)
);

CREATE TABLE Consultor (
    legajoConsultor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreApellidoConsultor VARCHAR2(150) NOT NULL,
    fechaHoraBajaConsultor TIMESTAMP
);

CREATE TABLE Cliente (
    dniCliente NUMBER PRIMARY KEY,
    codUsuario NUMBER NOT NULL,
    nombreApellidoCliente VARCHAR2(150) NOT NULL,
    fechaHoraBajaCliente TIMESTAMP,
    emailCliente VARCHAR2(150) NOT NULL
);

CREATE TABLE Tramite (
    numeroTramite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraIngresoTramite TIMESTAMP NOT NULL,
    fechaHoraFinReal TIMESTAMP,
    fechaHoraInicioReal TIMESTAMP,
    observacionesTramite VARCHAR2(255),
    fechaHoraLimiteTramiteDocumentacion TIMESTAMP,

    codTipoTramite NUMBER NOT NULL,
    codEstadoTramite NUMBER NOT NULL,
    legajoConsultor NUMBER NOT NULL,
    dniCliente NUMBER NOT NULL,

    CONSTRAINT tramite_tipo_tramite_fk
        FOREIGN KEY (codTipoTramite)
        REFERENCES TipoTramite(codTipoTramite),

    CONSTRAINT tramite_estado_tramite_fk
        FOREIGN KEY (codEstadoTramite)
        REFERENCES EstadoTramite(codEstadoTramite),

    CONSTRAINT tramite_consultor_fk
        FOREIGN KEY (legajoConsultor)
        REFERENCES Consultor(legajoConsultor),

    CONSTRAINT tramite_cliente_fk
        FOREIGN KEY (dniCliente)
        REFERENCES Cliente(dniCliente)
);

CREATE TABLE TramiteEstado (
    numeroTramite NUMBER NOT NULL,
    codEstadoTramite NUMBER NOT NULL,
    contadorTramiteEstado NUMBER NOT NULL,
    fechaHoraInicioTramiteEstado TIMESTAMP NOT NULL,
    fechaHoraFinTramiteEstado TIMESTAMP,
    observacionesTramiteEstado VARCHAR2(255),

    PRIMARY KEY (numeroTramite, codEstadoTramite, contadorTramiteEstado),

    FOREIGN KEY (numeroTramite)
        REFERENCES Tramite(numeroTramite),

    FOREIGN KEY (codEstadoTramite)
        REFERENCES EstadoTramite(codEstadoTramite)
);

CREATE TABLE ConfiguracionTipoTramite (
    nroConfiguracionTT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraInicioVigenciaTT TIMESTAMP NOT NULL,
    fechaHoraFinVigenciaTT TIMESTAMP
);

CREATE TABLE ConfiguracionTipoTramiteEstadoTramite (
    nroConfiguracionTT NUMBER NOT NULL,
    codEstadoTramite NUMBER NOT NULL,
    ordenTipoTramiteEstadoTramite NUMBER NOT NULL,

    PRIMARY KEY (nroConfiguracionTT, codEstadoTramite),

    CONSTRAINT config_tt_estado_config_fk
        FOREIGN KEY (nroConfiguracionTT)
        REFERENCES ConfiguracionTipoTramite(nroConfiguracionTT),

    CONSTRAINT config_tt_estado_estado_fk
        FOREIGN KEY (codEstadoTramite)
        REFERENCES EstadoTramite(codEstadoTramite)
);

CREATE TABLE TipoDocumentacion (
    codTipoDocumentacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraBajaTipoDocumentacion TIMESTAMP,
    nombreTipoDocumentacion VARCHAR2(100) NOT NULL,
    requiereEntregaWeb NUMBER(1) NOT NULL,

    CONSTRAINT tipo_doc_req_web_ck
        CHECK (requiereEntregaWeb IN (0, 1))
);

CREATE TABLE ConfiguracionDocumentacion (
    nroConfiguracionDocumentacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraInicioVigenciaTTTD TIMESTAMP NOT NULL,
    fechaHoraFinVigenciaTTTD TIMESTAMP,
    codTipoTramite NUMBER NOT NULL,

    CONSTRAINT config_doc_tipo_tramite_fk
        FOREIGN KEY (codTipoTramite)
        REFERENCES TipoTramite(codTipoTramite)
);

CREATE TABLE TipoTramiteTipoDocumentacion (
    nroConfiguracionDocumentacion NUMBER NOT NULL,
    codTipoDocumentacion NUMBER NOT NULL,

    PRIMARY KEY (nroConfiguracionDocumentacion, codTipoDocumentacion),

    CONSTRAINT tttd_config_doc_fk
        FOREIGN KEY (nroConfiguracionDocumentacion)
        REFERENCES ConfiguracionDocumentacion(nroConfiguracionDocumentacion),

    CONSTRAINT tttd_tipo_doc_fk
        FOREIGN KEY (codTipoDocumentacion)
        REFERENCES TipoDocumentacion(codTipoDocumentacion)
);

CREATE TABLE DocumentacionTramite (
    numeroTramite NUMBER NOT NULL,
    codTipoDocumentacion NUMBER NOT NULL,
    fechaHoraIngresoDocumentacion TIMESTAMP NOT NULL,
    urlDocumentacion VARCHAR2(255) NOT NULL,

    PRIMARY KEY (numeroTramite, codTipoDocumentacion, fechaHoraIngresoDocumentacion),

    CONSTRAINT doc_tramite_tramite_fk
        FOREIGN KEY (numeroTramite)
        REFERENCES Tramite(numeroTramite),

    CONSTRAINT doc_tramite_tipo_doc_fk
        FOREIGN KEY (codTipoDocumentacion)
        REFERENCES TipoDocumentacion(codTipoDocumentacion)
);

CREATE TABLE ConfiguracionAgenda (
    nroConfiguracionAgenda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraInicioVigenciaAgenda TIMESTAMP NOT NULL,
    fechaHoraFinVigenciaAgenda TIMESTAMP
);

CREATE TABLE ConfigAgendaConsultor (
    nroConfiguracionAgenda NUMBER NOT NULL,
    legajoConsultor NUMBER NOT NULL,
    cantMaximaTramites NUMBER NOT NULL,

    PRIMARY KEY (nroConfiguracionAgenda, legajoConsultor),

    CONSTRAINT config_agenda_consultor_config_fk
        FOREIGN KEY (nroConfiguracionAgenda)
        REFERENCES ConfiguracionAgenda(nroConfiguracionAgenda),

    CONSTRAINT config_agenda_consultor_consultor_fk
        FOREIGN KEY (legajoConsultor)
        REFERENCES Consultor(legajoConsultor)
);

CREATE TABLE ConfiguracionCosto (
    nroConfiguracionCosto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraInicioVigenciaCosto TIMESTAMP NOT NULL,
    fechaHoraFinVigenciaCosto TIMESTAMP
);

CREATE TABLE ConfiguracionCostoTT (
    nroConfiguracionCosto NUMBER NOT NULL,
    codTipoTramite NUMBER NOT NULL,
    montoCostoBase NUMBER(10,2) NOT NULL,

    PRIMARY KEY (nroConfiguracionCosto, codTipoTramite),

    CONSTRAINT config_costo_tt_config_fk
        FOREIGN KEY (nroConfiguracionCosto)
        REFERENCES ConfiguracionCosto(nroConfiguracionCosto),

    CONSTRAINT config_costo_tt_tipo_tramite_fk
        FOREIGN KEY (codTipoTramite)
        REFERENCES TipoTramite(codTipoTramite)
);
